version: "3.3"
services:
  postgres:
    build:
      context: ./Postgres
      dockerfile: postgres.Dockerfile
    env_file:
      - postgres.env
    restart: always
   #volumes:
   #  - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgbackups:
    build:
      context: ./PostgresBackup
      dockerfile: alpine.Dockerfile
    restart: always
    user: postgres:postgres
    volumes:
        - /var/opt/pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    env_file:
      - postgres.env
      - aws.env
      - rclone.env
    environment:
            - SAVE_TO_DISK=true
            - POSTGRES_HOST=postgres
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
            - SCHEDULE=@daily
            - HEALTHCHECK_PORT=8080
    
