version: "3.3"
services:
  postgres:
    build:
      context: ./Docker
      dockerfile: postgres.Dockerfile
    env_file:
      - postgres.env
    restart: always
   #volumes:
   #  - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
        - /var/opt/pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    env_file:
      - postgres.env
    environment:
            - POSTGRES_HOST=postgres
        #   - POSTGRES_DB=database
        #   - POSTGRES_USER=username
        #   - POSTGRES_PASSWORD=password
        #   - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=8080
    
